# 数据源
spring:
  application:
    name: attendance-security
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

# 自定义配置
attendance:
  security:
#    browserProperties:
#      loginResponseType: REDIRECT                # 登录重定向跳转,默认返回JSON
#      loginPage: /demo-sign.html                 # 设置默认登录页
#    code:
#      image:
#        length: 4                                # 验证码位数
#        width: 200                               # 验证码图形长度
#        url: /user,/user/*                       # 验证码使用接口
