# 数据源
spring:
  application:
    name: attendance-security
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

# 自定义配置
attendance:
  security:
    social:
      qq:
        app-id:
        app-secret:
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      browser:
        signUpUrl: /demo-sign-up.html
      social:
        filterProcessesUrl: /qqLogin