# 数据源
spring:
  application:
    name: attendance-security
  datasource:
    url: jdbc:postgresql://localhost:5432/japan_study
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
